### ISSUE TITLE
Static links to tag releases changed

### ISSUE THREAD

**Issue by leofang** [NVlabs/cub#182]
Hi @brycelelbach, something changed when you revised the release logs yesterday. We used to point to https://github.com/NVlabs/cub/archive/v1.8.0.tar.gz but now it changes to https://github.com/NVlabs/cub/archive/1.8.0.tar.gz (the "v" is missing). I think it is a breaking change. Any chance it could be reverted?

**Comment by leofang** [comment]
CI log:

https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=2572&view=logs&j=2928da41-3b64-5ab6-d69b-0a36120eed79&t=63f0ac55-36da-5f67-e095-598517af0be7&l=443

**Comment by brycelelbach** [comment]
Whoops, yes that was a mistake; the v tags should be left for compatibility
reasons. Can you update to point at the new tags though?

--
Bryce Adelstein Lelbach aka wash
US Programming Language Standards (PL22) Chair
ISO C++ Library Evolution Chair
CppCon and C++Now Program Chair
CUDA Core C++ Libraries (Thrust, CUB, libcu++) Lead @ NVIDIA
--

**Comment by leofang** [comment]
Thanks, Bryce. Yes we can, just wanna make sure it won't change again 🙂

**Comment by brycelelbach** [comment]
It won't change again. If you can just update to the new link, that would
be great

--
Bryce Adelstein Lelbach aka wash
US Programming Language Standards (PL22) Chair
ISO C++ Library Evolution Chair
CppCon and C++Now Program Chair
CUDA Core C++ Libraries (Thrust, CUB, libcu++) Lead @ NVIDIA
--

**Comment by brycelelbach** [comment]
Actually it would really be best if you just start using CUB from the CUDA
toolkit. You'll be broken by 11.0 anyways if you dont, as CUB and Thrust
are version locked.

--
Bryce Adelstein Lelbach aka wash
US Programming Language Standards (PL22) Chair
ISO C++ Library Evolution Chair
CppCon and C++Now Program Chair
CUDA Core C++ Libraries (Thrust, CUB, libcu++) Lead @ NVIDIA
--

**Comment by leofang** [comment]
> Actually it would really be best if you just start using CUB from the CUDA toolkit. You'll be broken by 11.0 anyways if you dont, as CUB and Thrust are version locked.

Hi Bryce, yes I was aware of this change, and in fact it was brought up recently (https://github.com/cupy/cupy/issues/3346). 

The problem for package and library providers is backward compatibility: I expect it takes a few more years for dropping CUDA 9 & 10 completely, and before that happens we need a way to build the CUB support, without or with the pretense of Thrust. (In CuPy the two supports are currently independent of each other.)

Plus, some advanced users may be unhappy with the shipped CUB version and want to stay up-to-date, so I think there will be a need to hack the locking mechanism you recently added to CUB and Thrust so as to make them decoupled. I would love to know if you have good suggestions.

**Comment by brycelelbach** [comment]
The best option to stay on an older version of CUB is to check out both an older version of CUB and an older version of Thrust.

**Comment by brycelelbach** [comment]
Fixed, up to 1.8.0, and just on the https://github.com/NVlabs/cub repo. For newer releases and the current development trunk https://github.com/thrust/cub, please use the `A.B.C` scheme instead of `vA.B.C`

**Comment by leofang** [comment]
Thanks for follow-up, @brycelelbach.

> Fixed, up to 1.8.0, and just on the https://github.com/NVlabs/cub repo. 

As of 12:18am, May 20, the link still does not contain the "v" prefix: https://github.com/NVlabs/cub/archive/1.8.0.tar.gz. Could it be that it takes a day or longer to reflect the changes? 

> For newer releases and the current development trunk https://github.com/thrust/cub, please use the `A.B.C` scheme instead of `vA.B.C`

Sounds good. My only question for the latest releases on NVlabs/cub: Are they meant to mirror what are available on Thrust/cub?

**Comment by leofang** [comment]
While I think it's best to have a separate issue on this discussion, for my own needs I am almost there, so let me continue 😅

> The best option to stay on an older version of CUB is to check out both an older version of CUB and an older version of Thrust.

So, if an application only needs CUB (as it can be used indep. of Thrust), it won't matter (as it was) what version(s) of Thrust are available in the include search path, right?

**Comment by brycelelbach** [comment]
https://github.com/NVlabs/cub/archive/v1.8.0.tar.gz

Works fine for me

--
Bryce Adelstein Lelbach aka wash
US Programming Language Standards (PL22) Chair
ISO C++ Library Evolution Chair
CppCon and C++Now Program Chair
CUDA Core C++ Libraries (Thrust, CUB, libcu++) Lead @ NVIDIA
--

**Comment by leofang** [comment]
Oh OK...So this is a hidden link not shown in the release notes.

**Comment by brycelelbach** [comment]
Yes; that is a legacy link. It will work but please don't rely on it for
future releases. We want one tagging scheme across all our libraries to
simplify our scripting and that scheme is `X.Y.Z`

--
Bryce Adelstein Lelbach aka wash
US Programming Language Standards (PL22) Chair
ISO C++ Library Evolution Chair
CppCon and C++Now Program Chair
CUDA Core C++ Libraries (Thrust, CUB, libcu++) Lead @ NVIDIA
--

**Comment by leofang** [comment]
Thanks, Bryce! https://github.com/NVlabs/cub/issues/182#issuecomment-631227729 is my last question 🙏

**Comment by brycelelbach** [comment]
CUB depends on Thrust; there's a circular dependency in some of the iterator headers. Depending on what you are using you may or may not depend on Thrust.

**Comment by leofang** [comment]
Thanks a lot, Bryce! So we better get some tests with newer CUB started, preferably before CUDA 11 is released so we have some time to make any necessary fix. 

I think the main thread is addressed, so are my side questions 😅 So I'm closing it.
